In [14]:
!pip install SQLAlchemy

Requirement already satisfied: SQLAlchemy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.0.29)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/codespace/.local/lib/python3.12/site-packages (from SQLAlchemy) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from SQLAlchemy) (3.3.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [ ]:
!pip install mysql-connector-python==8.3.0

Collecting mysql-connector-python==8.3.0
  Downloading mysql_connector_python-8.3.0-cp312-cp312-manylinux_2_17_x86_64.whl.metadata (1.9 kB)
Downloading mysql_connector_python-8.3.0-cp312-cp312-manylinux_2_17_x86_64.whl (21.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.5/21.5 MB 33.4 MB/s  0:00:00m0:00:010:01
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.3.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
!pip install mysqlclient==2.2.4

Collecting mysqlclient==2.2.4
  Downloading mysqlclient-2.2.4.tar.gz (90 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: mysqlclient
  Building wheel for mysqlclient (pyproject.toml) ... done
  Created wheel for mysqlclient: filename=mysqlclient-2.2.4-cp312-cp312-linux_x86_64.whl size=133327 sha256=679461f6c50673cc1e4429136433e4848954fe40d7979bb6781a5387d02c07bc
  Stored in directory: /home/codespace/.cache/pip/wheels/20/6f/c3/3b23bb01988b1c0bea0668e2116315ce43ced2179724ab593e
Successfully built mysqlclient
Installing collected packages: mysqlclient
Successfully installed mysqlclient-2.2.4

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [24]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [17]:
!pip install pandas==2.3.3

Collecting pandas==2.3.3
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas==2.3.3) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas==2.3.3) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas==2.3.3)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas==2.3.3) (2025.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.3.3) (1.17.0)
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 28.3 MB/s  0:00:00m0:00:010:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed pandas-2.3.3 pytz-2025.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
from sqlalchemy import create_engine, text

engine = create_engine("mysql://root:root@10.0.11.209:3310/retail_db")

df = pd.read_sql_table('departments', engine)

df

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop

In [3]:
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:root@10.0.11.209:3310/retail_db")

with engine.connect() as conn:
   df =  conn.execute(text("SELECT 1"))

In [4]:
with engine.connect() as conn:
   result =  conn.execute(text("SELECT * from departments"))
   df_departments = pd.DataFrame(result.fetchall(), columns=result.keys())

   result = conn.execute(text("SELECT * from customers"))
   df_customers = pd.DataFrame(result.fetchall(), columns=result.keys())

   result = conn.execute(text("SELECT * from orders"))
   df_orders = pd.DataFrame(result.fetchall(), columns=result.keys())

   result = conn.execute(text("SELECT * from order_items"))
   df_order_items = pd.DataFrame(result.fetchall(), columns=result.keys())

   result = conn.execute(text("SELECT * from categories"))
   df_categories = pd.DataFrame(result.fetchall(), columns=result.keys())

   result = conn.execute(text("SELECT * from products"))
   df_products = pd.DataFrame(result.fetchall(), columns=result.keys())


df_customers.head()

,customer_id,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode
0,1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521
1,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126
2,3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,00725
3,4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069
4,5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,00725

In [5]:
type(df_categories)

pandas.core.frame.DataFrame

In [6]:
# cuantos clientes hay por ciudad
# SELECT city, count(1) from customers group by city

df_customers['customer_city'].value_counts()

customer_city
Caguas           4584
Chicago           274
Brooklyn          225
Los Angeles       224
New York          120
                 ...
Hempstead           3
Freehold            2
Ponce               2
National City       2
Gwynn Oak           2
Name: count, Length: 562, dtype: int64

In [7]:
# cuantas categorias existen dentro de cada departamento

df_categories.groupby('category_department_id')['category_id'].count()

category_department_id
2     8
3     8
4     6
5     7
6    12
7     7
8    10
Name: category_id, dtype: int64

In [ ]:
# Caul es la distribucion de categorias por departamento
# ON a.id = b.id_tablaa 
# df = df_categories.merge(df_departments, on='department_id', how='left') -> la misma clave

df = df_categories.merge(df_departments, left_on='category_department_id', right_on='department_id', how='left')
df['department_name'].value_counts()

department_name
Outdoors    12
Fitness      8
Footwear     8
Golf         7
Fan Shop     7
Apparel      6
Name: count, dtype: int64

In [10]:
# precio promedio de productos

df_products['product_price'].mean()

np.float64(124.99633457249071)

In [14]:
# Cuales son los productos mas caro y mas barato

idx = df_products['product_price'].idxmax()

df_products.loc[idx]

product_id                                                           208
product_category_id                                                   10
product_name                                         SOLE E35 Elliptical
product_description
product_price                                                    1999.99
product_image          http://images.acmesports.sports/SOLE+E35+Ellip...
Name: 207, dtype: object

In [15]:
idx = df_products['product_price'].idxmin()

df_products.loc[idx]

product_id                                                            38
product_category_id                                                    3
product_name               Nike Men's Hypervenom Phantom Premium FG Socc
product_description
product_price                                                        0.0
product_image          http://images.acmesports.sports/Nike+Men%27s+H...
Name: 37, dtype: object

In [ ]:
# Cuales es la categoria mas popular en terminos de ventas

df = df_order_items.merge(df_products, left_on='order_item_product_id', right_on='product_id')
df_ventas = df.groupby('product_category_id')['order_item_subtotal'].sum().reset_index()

## Merge con df_categories

idx = df_ventas['order_item_subtotal'].idxmax()

df_ventas.loc[idx]

product_category_id         45.0
order_item_subtotal    6929653.5
Name: 30, dtype: float64

In [33]:
# Data Engineering
df_departments = pd.read_csv('../Sesion03/data_retail/departments', header=None, sep='|', names = ['department_id', 'department_name'])

In [52]:
df_categories = pd.read_csv('../Sesion03/data_retail/categories', header=None, sep='|', names = ['category_id', 'category_department_id', 'category_name'])

In [ ]:
def validar_duplicados(df, cuolumna):

    if df[cuolumna].duplicated().any():
        print(f'la columna {cuolumna} tiene registros duplicados')
        return True

    return False

In [35]:
if df_departments['department_name'].duplicated().any():
    print('el dataset tiene registro duplicado')

el dataset tiene registro duplicado

In [48]:
ids_validos = set(df_departments['department_id'])
ids_validos

{2, 3, 4, 5, 6, 7, 8}

In [57]:

if not df_categories['category_department_id'].isin(ids_validos).all():
    print('ids que no existen')

ids que no existen

In [59]:
# any() -> retorna un True si al menos un elemento es True
# all() ->  retorna un True si todos son True

def validar_integridad(df, ids_validos, columna):
    if not df[columna].isin(ids_validos).all():
        print('contiene ids invalidos')

In [60]:
validar_integridad(df_categories, ids_validos, 'category_department_id')

contiene ids invalidos

In [67]:
df_orders = pd.read_csv('../Sesion03/data_retail/orders', header=None, sep='|', names = ['order_id', 'order_date', 'order_customer_id', 'order_status'])
df_orders.head()

   order_id             order_date  order_customer_id     order_status
0         1  2013-07-25 00:00:00.0              11599           CLOSED
1         2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2         3  2013-07-25 00:00:00.0              12111         COMPLETE
3         4  2013-07-25 00:00:00.0               8827           CLOSED
4         5  2013-07-25 00:00:00.0              11318         COMPLETE

In [69]:
df_orders['order_date'] = pd.to_datetime(df_orders['order_date'], errors = 'coerce') # NaT - El proceso no se rompa

In [70]:
df_orders.head(20)

    order_id order_date  order_customer_id     order_status
0          1 2013-07-25              11599           CLOSED
1          2 2013-07-25                256  PENDING_PAYMENT
2          3 2013-07-25              12111         COMPLETE
3          4 2013-07-25               8827           CLOSED
4          5 2013-07-25              11318         COMPLETE
5          6 2013-07-25               7130         COMPLETE
6          7 2013-07-25               4530         COMPLETE
7          8        NaT               2911       PROCESSING
8          9 2013-07-25               5657  PENDING_PAYMENT
9         10 2013-07-25               5648  PENDING_PAYMENT
10        11 2013-07-25                918   PAYMENT_REVIEW
11        12 2013-07-25               1837           CLOSED
12        13 2013-07-25               9149  PENDING_PAYMENT
13        14 2013-07-25               9842       PROCESSING
14        15        NaT               2568         COMPLETE
15        16 2013-07-25               7276  PENDING_PAYMENT
16        17 2013-07-25               2667         COMPLETE
17        18 2013-07-25               1205           CLOSED
18        19 2013-07-25               9488  PENDING_PAYMENT
19        20 2013-07-25               9198       PROCESSING

In [ ]:
def save_data(df, table, engine):
    df.to_sql(table, engine, if_exists='replace')

68883

In [74]:
df = pd.read_sql_table('oders_2', engine)
df

       index  order_id order_date  order_customer_id     order_status
0          0         1 2013-07-25              11599           CLOSED
1          1         2 2013-07-25                256  PENDING_PAYMENT
2          2         3 2013-07-25              12111         COMPLETE
3          3         4 2013-07-25               8827           CLOSED
4          4         5 2013-07-25              11318         COMPLETE
...      ...       ...        ...                ...              ...
68878  68878     68879 2014-07-09                778         COMPLETE
68879  68879     68880 2014-07-13               1117         COMPLETE
68880  68880     68881 2014-07-19               2518  PENDING_PAYMENT
68881  68881     68882 2014-07-22              10000          ON_HOLD
68882  68882     68883 2014-07-23               5533         COMPLETE

[68883 rows x 5 columns]